### ISSUE TITLE
License needed

### ISSUE THREAD

**Issue by alexpeachey** [Originate/nitroglycerin#4]
Please add a license to this project.

**Comment by charlierudolph** [comment]
@kevgo you okay with MIT?

**Comment by charlierudolph** [comment]
Actually the package.json already specifies ISC. I'll add an actual license file with that

**Comment by charlierudolph** [comment]
Nevermind going to use MIT for now since that's what appears on quite a few other projects

**Comment by kevgo** [comment]
Both are okay choices here.
